export const FETCH_PRODUCT_INFO = 'FETCH_PRODUCT_INFO';
export const FETCH_PRODUCT_INFO_START = 'FETCH_PRODUCT_INFO_START';
export const FETCH_PRODUCT_INFO_SUCCESS = 'FETCH_PRODUCT_INFO_SUCCESS';
export const FETCH_PRODUCT_INFO_FAIL = 'FETCH_PRODUCT_INFO_FAIL';
export const FETCH_SELLERS_SUCCESS = 'FETCH_SELLERS_SUCCESS';

export const ADD_PRODUCT_TO_FAVORITES = 'ADD_PRODUCT_TO_FAVORITES';
export const REMOVE_PRODUCT_FROM_FAVORITES = 'REMOVE_PRODUCT_FROM_FAVORITES';
export const RETRIEVE_FAVORITES_FROM_LOCALSTORAGE = 'RETRIEVE_FAVORITES_FROM_LOCALSTORAGE';
export const SET_FAVORITES_TO_STATE = 'SET_FAVORITES_TO_STATE';

export const UPDATE_CATEGORY_FILTER = 'UPDATE_CATEGORY_FILTER';
export const UPDATE_PRICE_FILTER = 'UPDATE_PRICE_FILTER';
export const UPDATE_FAVORITES_ONLY_FILTER = 'UPDATE_FAVORITES_ONLY_FILTER';

export const UPDATE_SORTING_OPTION = 'UPDATE_SORTING_OPTION';

